
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/niels/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 5.4.0-169-generic - x86_64
...
